#!/bin/bash

DIR=/home/stdin/bot/data/apt

for DIST in "$DIR"/*.list; do
    test -h $DIST && continue
    DIST=${DIST:${#DIR}}
    DIST=${DIST/.list}
    mkdir -p "$DIR/apt-file/$DIST"
    apt-file -l -c "$DIR/apt-file/$DIST" -s "$DIR/$DIST.list" update >/dev/null 2>&1
    RET=$?
    if [ ! $RET ]; then
        echo "apt-file failed for $DIST!"
    fi
done
